/* tests/support/fake_platform.h */
#ifndef FAKE_PLATFORM_H
#define FAKE_PLATFORM_H

#include "micro_opcua/platform.h"

/* tests/support/fake_platform.c returns entropy byte 0x42. The first
   CreateSession authenticationToken generated by src/services/session.c is
   0x42424242 ^ 0xA5A5A5A5. */
#define TEST_FAKE_FIRST_AUTH_TOKEN 0xE7E7E7E7u

#ifdef __cplusplus
extern "C" {
#endif

/* Initialize the fake platform and return adapters for tests */
void fake_platform_init(mu_tcp_adapter_t *tcp_adapter, mu_time_adapter_t *time_adapter,
                        mu_entropy_adapter_t *entropy_adapter);

#ifdef __cplusplus
}
#endif

#endif /* FAKE_PLATFORM_H */
